# Морфологічний аналіз - ризики

In [4]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
sns.set_style('whitegrid')
# Jupyter rendering stuff
from IPython.display import display, Math, Latex, HTML, clear_output
import itertools

## Data generation

In [1]:
def generate_probabilities(*sizes):
    result = [np.random.random(size) for size in sizes]
    for vec in result:
        vec /= np.sum(vec)
    return result

In [16]:
factor_s = (2,3,4)
risks_no = 2
factor_eta = [generate_probabilities(*factor_s) for r in range(risks_no)]
factor_W =   [generate_probabilities(*factor_s) for r in range(risks_no)]

## Setting constants

In [12]:
eta_ranges = W_ranges = np.array([0, 0.1, 0.3, 0.5, 0.7, 0.9, 1])
# to review

## Calculating risks

In [20]:
def aggregate_risk_values(splitted_values):
    result = []
    for tup in zip(*splitted_values):
        result.append(1 - np.prod(1 - np.vstack(tup), axis=0))
    return result

In [25]:
eta = aggregate_risk_values(factor_eta)
W =   aggregate_risk_values(factor_W)

([array([ 0.88210306,  0.73014592]),
  array([ 0.35285706,  0.73960981,  0.56213555]),
  array([ 0.58176084,  0.11311378,  0.36628775,  0.64106912])],
 [array([ 0.42761232,  0.95581969]),
  array([ 0.69507606,  0.58317388,  0.42464573]),
  array([ 0.55964776,  0.14737052,  0.55147262,  0.46041602])])